version: "3"
services:
  db:
    image: postgres
    container_name: beer_db
    restart: always
    env_file:
      - .env
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: "admin"
      POSTGRES_USER: "admin"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U admin" ]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    image: beer_api:1.0.0
    container_name: beer_api
    build: .
    restart: always
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "8080:8080"
    env_file:
      - .env
    healthcheck:
      test: ["CMD", "curl", "--fail", "--silent", "http://localhost:8080/api/v1/health"]
      interval: 5s
      timeout: 10s
      retries: 12

volumes:
  db-data: